// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDHZiTpHqf1kQ99wQSRLBw4IsA0r__1k',
    appId: '1:160959633928:android:cae4cc1c23821ea26c4fbd',
    messagingSenderId: '160959633928',
    projectId: 'petroglifos-software',
    storageBucket: 'petroglifos-software.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi6iVMLd0gtkOuw69X443wm3EhpZf8Xgc',
    appId: '1:160959633928:ios:66469e4b04db1de06c4fbd',
    messagingSenderId: '160959633928',
    projectId: 'petroglifos-software',
    storageBucket: 'petroglifos-software.firebasestorage.app',
    iosBundleId: 'com.example.softwarePetroglifos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi6iVMLd0gtkOuw69X443wm3EhpZf8Xgc',
    appId: '1:160959633928:ios:66469e4b04db1de06c4fbd',
    messagingSenderId: '160959633928',
    projectId: 'petroglifos-software',
    storageBucket: 'petroglifos-software.firebasestorage.app',
    iosBundleId: 'com.example.softwarePetroglifos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC6-nsbm1kYV_zAWTzltRdDPJvH_gVCyM',
    appId: '1:160959633928:web:cc026f5857702fe06c4fbd',
    messagingSenderId: '160959633928',
    projectId: 'petroglifos-software',
    authDomain: 'petroglifos-software.firebaseapp.com',
    storageBucket: 'petroglifos-software.firebasestorage.app',
    measurementId: 'G-5CYZL6Z0MT',
  );
}
